## Epoch from .fif files and save
This is useful for running before the time frequency representation script

In [2]:
import sys
import mne
from mne import preprocessing
import pandas as pd
from mne.io import read_raw_eeglab
from mne.io import eeglab
import numpy as np
import os.path
from os import path
from autoreject import get_rejection_threshold

In [3]:
# parameters
cap_size = 'medium' # either 'small', 'medium' or 'large'
ppt_num = '3'
session = '3' #either 1, 2 or 3



In [4]:
pathdata = 'sub'+ppt_num+'_sess'+session+'_50_ica_eeg.fif' 
xpath = 'X:\\CompSci\\ResearchProjects\\EJONeill\\Neuroimaging\\multisensoryeeg\\openNeuro\\sourcedata\\preprocessed\\'
pathdata = xpath + pathdata

### Load up the raw .fif file

In [5]:
raw = mne.io.read_raw_fif(pathdata)

Opening raw data file X:\CompSci\ResearchProjects\EJONeill\Neuroimaging\multisensoryeeg\openNeuro\sourcedata\preprocessed\sub3_sess3_50_ica_eeg.fif...
    Range : 0 ... 4326399 =      0.000 ...  4224.999 secs
Ready.
Opening raw data file X:\CompSci\ResearchProjects\EJONeill\Neuroimaging\multisensoryeeg\openNeuro\sourcedata\preprocessed\sub3_sess3_50_ica_eeg-1.fif...
    Range : 4326400 ... 4930237 =   4225.000 ...  4814.685 secs
Ready.


### Reject Bad Epochs based on Automatic Thresholding

In [6]:
events, event_ids = mne.events_from_annotations(raw, verbose = False)
print("The events...", events)
epochs = mne.Epochs(raw=raw, events=events, event_id=event_ids, preload=True, tmin = 0,tmax =4,baseline=None, event_repeated='merge')
reject = get_rejection_threshold(epochs, ch_types='eeg', decim=2)
epochs.drop_bad(reject=reject)
print("The number of distinct events, not trials :", len(event_ids)) # this will give the number of distinct events, not the amount of trials
print("The event names ", event_ids)

The events... [[      0       0     100]
 [  38080       0     201]
 [  50338       0     200]
 ...
 [4894116       0      64]
 [4902309       0     201]
 [4930235       0     100]]
Not setting metadata
923 matching events found
No baseline correction applied
0 projection items activated
Loading data for 923 events and 4097 original time points ...
1 bad epochs dropped


C:\Users\hlw69\Anaconda3\lib\site-packages\autoreject\autoreject.py:244: RuntimeWarning: The measurement information indicates a low-pass frequency of 512 Hz. The decim=2 parameter will result in a sampling frequency of 512 Hz, which can cause aliasing artifacts.
  epochs.decimate(decim=decim)


Estimating rejection dictionary for eeg


C:\Users\hlw69\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\hlw69\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 678, in _fit_and_score
    estimator.fit(X_train, **fit_params)
  File "C:\Users\hlw69\Anaconda3\lib\site-packages\autoreject\autoreject.py", line 193, in fit
    self.mean_ = _slicemean(X, keep, axis=0)
  File "C:\Users\hlw69\Anaconda3\lib\site-packages\autoreject\autoreject.py", line 44, in _slicemean
    if len(obj[this_slice]) > 0:
numpy.core._exceptions._ArrayMemoryError: Unable

C:\Users\hlw69\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\hlw69\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 678, in _fit_and_score
    estimator.fit(X_train, **fit_params)
  File "C:\Users\hlw69\Anaconda3\lib\site-packages\autoreject\autoreject.py", line 193, in fit
    self.mean_ = _slicemean(X, keep, axis=0)
  File "C:\Users\hlw69\Anaconda3\lib\site-packages\autoreject\autoreject.py", line 44, in _slicemean
    if len(obj[this_slice]) > 0:
numpy.core._exceptions._ArrayMemoryError: Unable

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

## Grouping into Categories


We saw in the previous step that there are a huge number of unique events. They are currently not grouped into the 18 categories that we are interested in, which are combinations or Imagination or Perception; Flower or Penguin or Guitar; Sound or Text or Pictorial. The following code is clunky, but essentially sorts all of the event_ids into their corresponding category.

In [ ]:
imag_flower_t = []
imag_penguin_t = []
imag_guitar_t = []
imag_flower_p = []
imag_guitar_p = []
imag_penguin_p = []
imag_flower_s = []
imag_guitar_s = []
imag_penguin_s = []
perc_flower_t = []
perc_guitar_t = []
perc_penguin_t = []
perc_flower_p = []
perc_guitar_p = []
perc_penguin_p = []
perc_flower_s = []
perc_guitar_s = []
perc_penguin_s = []

for id in event_ids:
    if 'Imagination' in id:
        if 'flower' in id:
            if '_t_' in id:
                imag_flower_t.append(id)
            elif '_image_'in id:
                imag_flower_p.append(id)
            elif '_a_' in id:
                imag_flower_s.append(id)
            else:
                print(id)
        elif 'guitar' in id:
            if '_t_' in id:
                imag_guitar_t.append(id)
            elif '_image_'in id:
                imag_guitar_p.append(id)
            elif '_a_'in id:
                imag_guitar_s.append(id)
            else:
                print(id)
        elif 'penguin' in id:
            if '_t_' in id:
                imag_penguin_t.append(id)
            elif '_image_'in id:
                imag_penguin_p.append(id)
            elif '_a_'in id:
                imag_penguin_s.append(id)
            else:
                print(id)
                
    
    
    if 'Perception' in id:
        if 'flower' in id:
           # print(id)
            if '_t_' in id:
                perc_flower_t.append(id)
            elif '_image_' in id:
                perc_flower_p.append(id)
            elif 'a_'in id or 'audio' in id:
                perc_flower_s.append(id)
            else:
                print(id)
        elif 'guitar' in id:
            if '_t_' in id:
                perc_guitar_t.append(id)
            elif '_image_'in id:
                perc_guitar_p.append(id)
            elif 'tiona_'in id or 'audio' in id:
                perc_guitar_s.append(id)
            else:
                print(id)
        elif 'penguin' in id:
            if '_t_' in id:
                perc_penguin_t.append(id)
            elif '_image_'in id:
                perc_penguin_p.append(id)
            elif 'tiona_'in id or 'audio' in id:
                perc_penguin_s.append(id)
            else:
                print(id)

event_list = [imag_flower_t,imag_penguin_t, imag_guitar_t, imag_flower_p,imag_guitar_p,
             imag_penguin_p,imag_flower_s, imag_guitar_s, imag_penguin_s,
            perc_flower_t, perc_guitar_t, perc_penguin_t, perc_flower_p,
            perc_guitar_p, perc_penguin_p, perc_flower_s, perc_guitar_s, perc_penguin_s]
print("There should be 18 conditions: ", len(event_list))
for li in event_list:
    print("Amount of different types in each condition ",len(li))

In [15]:
# merge all the trials into their conditions, do this inplace to save on memory load

mne.epochs.combine_event_ids(epochs, imag_flower_t, {'imag_flower_t': 300}, copy = False)
mne.epochs.combine_event_ids(epochs, imag_penguin_t, {'imag_penguin_t': 301}, copy = False)
mne.epochs.combine_event_ids(epochs, imag_guitar_t, {'imag_guitar_t': 302}, copy = False)

mne.epochs.combine_event_ids(epochs, imag_flower_p, {'imag_flower_p': 303}, copy = False)
mne.epochs.combine_event_ids(epochs, imag_penguin_p, {'imag_penguin_p': 304}, copy = False)
mne.epochs.combine_event_ids(epochs, imag_guitar_p, {'imag_guitar_p': 305}, copy = False)

mne.epochs.combine_event_ids(epochs, imag_flower_s, {'imag_flower_s': 306}, copy = False)
mne.epochs.combine_event_ids(epochs, imag_penguin_s, {'imag_penguin_s': 307}, copy = False)
mne.epochs.combine_event_ids(epochs, imag_guitar_s, {'imag_guitar_s': 308}, copy = False)


mne.epochs.combine_event_ids(epochs, perc_flower_t, {'perc_flower_t': 309}, copy = False)
mne.epochs.combine_event_ids(epochs, perc_penguin_t, {'perc_penguin_t': 310}, copy = False)
mne.epochs.combine_event_ids(epochs, perc_guitar_t, {'perc_guitar_t': 311}, copy = False)

mne.epochs.combine_event_ids(epochs, perc_flower_p, {'perc_flower_p': 312}, copy = False)
mne.epochs.combine_event_ids(epochs, perc_penguin_p, {'perc_penguin_p': 313}, copy = False)
mne.epochs.combine_event_ids(epochs, perc_guitar_p, {'perc_guitar_p': 314}, copy = False)

mne.epochs.combine_event_ids(epochs, perc_flower_s, {'perc_flower_s': 315}, copy = False)
mne.epochs.combine_event_ids(epochs, perc_penguin_s, {'perc_penguin_s': 316}, copy = False)
mne.epochs.combine_event_ids(epochs, perc_guitar_s, {'perc_guitar_s': 317}, copy = False)


<Epochs |  722 events (all good), 0 - 4 sec, baseline off, ~2.76 GB, data loaded,
 '0, Impedance': 0
 '0, end_baseline###my_stream_name': 6
 '0, start_baseline###my_stream_name': 1
 'imag_flower_t': 37
 'imag_penguin_t': 42
 'imag_guitar_t': 35
 'imag_flower_p': 42
 'imag_penguin_p': 42
 'imag_guitar_p': 36
 'imag_flower_s': 43
 and 11 more events ...>

In [7]:
# keep only new selection of epochs 


epochs_of_interest  = ['imag_flower_t','imag_penguin_t', 'imag_guitar_t', 'imag_flower_p','imag_guitar_p',
             'imag_penguin_p','imag_flower_s', 'imag_guitar_s', 'imag_penguin_s',
            'perc_flower_t', 'perc_guitar_t', 'perc_penguin_t', 'perc_flower_p',
            'perc_guitar_p', 'perc_penguin_p', 'perc_flower_s', 'perc_guitar_s', 'perc_penguin_s']
epochs_sub = epochs[epochs_of_interest]

KeyError: 'Event name "perc_penguin_s" could not be found. The following events are present in the data: 0, Imagination_a_flower_high_10###my_stream_name, 0, Imagination_a_flower_high_11###my_stream_name, 0, Imagination_a_flower_high_17###my_stream_name, 0, Imagination_a_flower_high_23###my_stream_name, 0, Imagination_a_flower_high_4###my_stream_name, 0, Imagination_a_flower_high_5###my_stream_name, 0, Imagination_a_flower_low_10###my_stream_name, 0, Imagination_a_flower_low_13###my_stream_name, 0, Imagination_a_flower_low_17###my_stream_name, 0, Imagination_a_flower_low_23###my_stream_name, 0, Imagination_a_flower_low_25###my_stream_name, 0, Imagination_a_flower_low_5###my_stream_name, 0, Imagination_a_flower_normal_10###my_stream_name, 0, Imagination_a_flower_normal_11###my_stream_name, 0, Imagination_a_flower_normal_12###my_stream_name, 0, Imagination_a_flower_normal_16###my_stream_name, 0, Imagination_a_flower_normal_17###my_stream_name, 0, Imagination_a_flower_normal_19###my_stream_name, 0, Imagination_a_flower_normal_21###my_stream_name, 0, Imagination_a_flower_normal_22###my_stream_name, 0, Imagination_a_flower_normal_23###my_stream_name, 0, Imagination_a_flower_normal_24###my_stream_name, 0, Imagination_a_flower_normal_3###my_stream_name, 0, Imagination_a_flower_normal_5###my_stream_name, 0, Imagination_a_flower_normal_6###my_stream_name, 0, Imagination_a_guitar_high_11###my_stream_name, 0, Imagination_a_guitar_high_14###my_stream_name, 0, Imagination_a_guitar_high_18###my_stream_name, 0, Imagination_a_guitar_high_19###my_stream_name, 0, Imagination_a_guitar_high_25###my_stream_name, 0, Imagination_a_guitar_high_5###my_stream_name, 0, Imagination_a_guitar_low_10###my_stream_name, 0, Imagination_a_guitar_low_17###my_stream_name, 0, Imagination_a_guitar_low_19###my_stream_name, 0, Imagination_a_guitar_low_25###my_stream_name, 0, Imagination_a_guitar_low_3###my_stream_name, 0, Imagination_a_guitar_low_6###my_stream_name, 0, Imagination_a_guitar_normal_1###my_stream_name, 0, Imagination_a_guitar_normal_10###my_stream_name, 0, Imagination_a_guitar_normal_11###my_stream_name, 0, Imagination_a_guitar_normal_12###my_stream_name, 0, Imagination_a_guitar_normal_14###my_stream_name, 0, Imagination_a_guitar_normal_17###my_stream_name, 0, Imagination_a_guitar_normal_18###my_stream_name, 0, Imagination_a_guitar_normal_19###my_stream_name, 0, Imagination_a_guitar_normal_22###my_stream_name, 0, Imagination_a_guitar_normal_25###my_stream_name, 0, Imagination_a_guitar_normal_3###my_stream_name, 0, Imagination_a_guitar_normal_6###my_stream_name, 0, Imagination_a_guitar_normal_9###my_stream_name, 0, Imagination_a_penguin_high_10###my_stream_name, 0, Imagination_a_penguin_high_12###my_stream_name, 0, Imagination_a_penguin_high_25###my_stream_name, 0, Imagination_a_penguin_high_5###my_stream_name, 0, Imagination_a_penguin_high_6###my_stream_name, 0, Imagination_a_penguin_high_9###my_stream_name, 0, Imagination_a_penguin_low_10###my_stream_name, 0, Imagination_a_penguin_low_15###my_stream_name, 0, Imagination_a_penguin_low_19###my_stream_name, 0, Imagination_a_penguin_low_22###my_stream_name, 0, Imagination_a_penguin_low_25###my_stream_name, 0, Imagination_a_penguin_low_6###my_stream_name, 0, Imagination_a_penguin_normal_1 ###my_stream_name, 0, Imagination_a_penguin_normal_10###my_stream_name, 0, Imagination_a_penguin_normal_11###my_stream_name, 0, Imagination_a_penguin_normal_15###my_stream_name, 0, Imagination_a_penguin_normal_16###my_stream_name, 0, Imagination_a_penguin_normal_19###my_stream_name, 0, Imagination_a_penguin_normal_25###my_stream_name, 0, Imagination_a_penguin_normal_3###my_stream_name, 0, Imagination_a_penguin_normal_4###my_stream_name, 0, Imagination_a_penguin_normal_5###my_stream_name, 0, Imagination_a_penguin_normal_6###my_stream_name, 0, Imagination_a_penguin_normal_9###my_stream_name, 0, Imagination_audio_a_guitar_normal_10###my_stream_name, 0, Imagination_image_flower_c###my_stream_name, 0, Imagination_image_flower_m###my_stream_name, 0, Imagination_image_flower_s###my_stream_name, 0, Imagination_image_guitar_c###my_stream_name, 0, Imagination_image_guitar_m###my_stream_name, 0, Imagination_image_guitar_s###my_stream_name, 0, Imagination_image_penguin_c###my_stream_name, 0, Imagination_image_penguin_m###my_stream_name, 0, Imagination_image_penguin_s###my_stream_name, 0, Imagination_t_flower_1###my_stream_name, 0, Imagination_t_flower_2###my_stream_name, 0, Imagination_t_flower_3###my_stream_name, 0, Imagination_t_flower_4###my_stream_name, 0, Imagination_t_flower_5###my_stream_name, 0, Imagination_t_guitar_1###my_stream_name, 0, Imagination_t_guitar_2###my_stream_name, 0, Imagination_t_guitar_3###my_stream_name, 0, Imagination_t_guitar_4###my_stream_name, 0, Imagination_t_guitar_5###my_stream_name, 0, Imagination_t_penguin_1###my_stream_name, 0, Imagination_t_penguin_2###my_stream_name, 0, Imagination_t_penguin_3###my_stream_name, 0, Imagination_t_penguin_4###my_stream_name, 0, Imagination_t_penguin_5###my_stream_name, 0, Impedance, 0, Perception_image_flower_c###my_stream_name, 0, Perception_image_flower_m###my_stream_name, 0, Perception_image_flower_s###my_stream_name, 0, Perception_image_guitar_c###my_stream_name, 0, Perception_image_guitar_m###my_stream_name, 0, Perception_image_guitar_s###my_stream_name, 0, Perception_image_penguin_c###my_stream_name, 0, Perception_image_penguin_m###my_stream_name, 0, Perception_image_penguin_s###my_stream_name, 0, Perception_t_flower_1###my_stream_name, 0, Perception_t_flower_2###my_stream_name, 0, Perception_t_flower_3###my_stream_name, 0, Perception_t_flower_4###my_stream_name, 0, Perception_t_flower_5###my_stream_name, 0, Perception_t_guitar_1###my_stream_name, 0, Perception_t_guitar_2###my_stream_name, 0, Perception_t_guitar_3###my_stream_name, 0, Perception_t_guitar_4###my_stream_name, 0, Perception_t_guitar_5###my_stream_name, 0, Perception_t_penguin_1###my_stream_name, 0, Perception_t_penguin_2###my_stream_name, 0, Perception_t_penguin_3###my_stream_name, 0, Perception_t_penguin_4###my_stream_name, 0, Perception_t_penguin_5###my_stream_name, 0, Perceptiona_flower_high_10###my_stream_name, 0, Perceptiona_flower_high_11###my_stream_name, 0, Perceptiona_flower_high_17###my_stream_name, 0, Perceptiona_flower_high_23###my_stream_name, 0, Perceptiona_flower_high_4###my_stream_name, 0, Perceptiona_flower_high_5###my_stream_name, 0, Perceptiona_flower_low_10###my_stream_name, 0, Perceptiona_flower_low_13###my_stream_name, 0, Perceptiona_flower_low_17###my_stream_name, 0, Perceptiona_flower_low_23###my_stream_name, 0, Perceptiona_flower_low_25###my_stream_name, 0, Perceptiona_flower_low_5###my_stream_name, 0, Perceptiona_flower_normal_10###my_stream_name, 0, Perceptiona_flower_normal_11###my_stream_name, 0, Perceptiona_flower_normal_12###my_stream_name, 0, Perceptiona_flower_normal_16###my_stream_name, 0, Perceptiona_flower_normal_17###my_stream_name, 0, Perceptiona_flower_normal_19###my_stream_name, 0, Perceptiona_flower_normal_21###my_stream_name, 0, Perceptiona_flower_normal_22###my_stream_name, 0, Perceptiona_flower_normal_23###my_stream_name, 0, Perceptiona_flower_normal_24###my_stream_name, 0, Perceptiona_flower_normal_3###my_stream_name, 0, Perceptiona_flower_normal_5###my_stream_name, 0, Perceptiona_flower_normal_6###my_stream_name, 0, Perceptiona_guitar_high_11###my_stream_name, 0, Perceptiona_guitar_high_14###my_stream_name, 0, Perceptiona_guitar_high_18###my_stream_name, 0, Perceptiona_guitar_high_19###my_stream_name, 0, Perceptiona_guitar_high_25###my_stream_name, 0, Perceptiona_guitar_high_5###my_stream_name, 0, Perceptiona_guitar_low_10###my_stream_name, 0, Perceptiona_guitar_low_17###my_stream_name, 0, Perceptiona_guitar_low_19###my_stream_name, 0, Perceptiona_guitar_low_25###my_stream_name, 0, Perceptiona_guitar_low_3###my_stream_name, 0, Perceptiona_guitar_low_6###my_stream_name, 0, Perceptiona_guitar_normal_1###my_stream_name, 0, Perceptiona_guitar_normal_10###my_stream_name, 0, Perceptiona_guitar_normal_11###my_stream_name, 0, Perceptiona_guitar_normal_12###my_stream_name, 0, Perceptiona_guitar_normal_14###my_stream_name, 0, Perceptiona_guitar_normal_17###my_stream_name, 0, Perceptiona_guitar_normal_18###my_stream_name, 0, Perceptiona_guitar_normal_19###my_stream_name, 0, Perceptiona_guitar_normal_22###my_stream_name, 0, Perceptiona_guitar_normal_25###my_stream_name, 0, Perceptiona_guitar_normal_3###my_stream_name, 0, Perceptiona_guitar_normal_6###my_stream_name, 0, Perceptiona_guitar_normal_9###my_stream_name, 0, Perceptiona_penguin_high_10###my_stream_name, 0, Perceptiona_penguin_high_12###my_stream_name, 0, Perceptiona_penguin_high_25###my_stream_name, 0, Perceptiona_penguin_high_5###my_stream_name, 0, Perceptiona_penguin_high_6###my_stream_name, 0, Perceptiona_penguin_high_9###my_stream_name, 0, Perceptiona_penguin_low_10###my_stream_name, 0, Perceptiona_penguin_low_15###my_stream_name, 0, Perceptiona_penguin_low_19###my_stream_name, 0, Perceptiona_penguin_low_22###my_stream_name, 0, Perceptiona_penguin_low_25###my_stream_name, 0, Perceptiona_penguin_low_6###my_stream_name, 0, Perceptiona_penguin_normal_1 ###my_stream_name, 0, Perceptiona_penguin_normal_10###my_stream_name, 0, Perceptiona_penguin_normal_11###my_stream_name, 0, Perceptiona_penguin_normal_15###my_stream_name, 0, Perceptiona_penguin_normal_16###my_stream_name, 0, Perceptiona_penguin_normal_19###my_stream_name, 0, Perceptiona_penguin_normal_25###my_stream_name, 0, Perceptiona_penguin_normal_3###my_stream_name, 0, Perceptiona_penguin_normal_4###my_stream_name, 0, Perceptiona_penguin_normal_5###my_stream_name, 0, Perceptiona_penguin_normal_6###my_stream_name, 0, Perceptiona_penguin_normal_9###my_stream_name, 0, Perceptionaudio_a_guitar_normal_10###my_stream_name, 0, end_baseline###my_stream_name, 0, start_baseline###my_stream_name'

## Editing the Durations
Epochs in mne are expected to all be the same length. That is why in the *mne.Epochs()* method to extract epochs from the raw data, we set *tmin=0* and *tmax=4*, which takes a 4 second segment for each event. However, in our dataset, the time segment varies depending on the condition:
* Imagine Orthographic =  4s
* Perception Orthographic = 3s
* Imagine Audio =  4s  
* Perception Audio = 2s
* Imagine Pictorial =  4s
* Perception Pictorial = 3s

In the following code, we create a new epochs object for each condition to adjust for the different durations. We should end up with 6 different epoch objects. Suggestion for how to do this was taken from https://mne.discourse.group/t/epochs-with-variable-durations-again/2449 and https://mail.nmr.mgh.harvard.edu/pipermail//mne_analysis/2013-December/001741.html

In [17]:
imagine_orthographic_epochs = epochs_sub[['imag_flower_t', 'imag_guitar_t', 'imag_penguin_t']].crop(tmin=0, tmax =4)
imagine_pictorial_epochs = epochs_sub[['imag_flower_p', 'imag_guitar_p', 'imag_penguin_p']].crop(tmin=0, tmax =4)
imagine_audio_epochs = epochs_sub[['imag_flower_s', 'imag_guitar_s', 'imag_penguin_s']].crop(tmin=0, tmax =4)
perception_orthographic_epochs = epochs_sub[['perc_flower_t', 'perc_guitar_t', 'perc_penguin_t']].crop(tmin=0, tmax =3)
perception_pictorial_epochs = epochs_sub[['perc_flower_p', 'perc_guitar_p', 'perc_penguin_p']].crop(tmin=0, tmax =3)
perception_audio_epochs = epochs_sub[['perc_flower_s', 'perc_guitar_s', 'perc_penguin_s']].crop(tmin=0, tmax =2)
print(perception_audio_epochs,perception_orthographic_epochs, perception_pictorial_epochs,imagine_audio_epochs,imagine_orthographic_epochs, imagine_pictorial_epochs)

<Epochs |  114 events (all good), 0 - 3 sec, baseline off, ~334.3 MB, data loaded,
 'perc_flower_p': 39
 'perc_penguin_p': 40
 'perc_guitar_p': 35>


## Save Epochs to file based on condition 
Subjects get mixed together

In [18]:
epochs_fname = 'X:\\CompSci\\ResearchProjects\\EJONeill\\Neuroimaging\\multisensoryeeg\\processed_eeg\\epochs\\'# 'sample-epo.fif')


imagine_orthographic_epochs.save(epochs_fname+'imagine_orthographic\\'+ppt_num+'_'+session+'_epo.fif',overwrite=True)
imagine_pictorial_epochs.save(epochs_fname+'imagine_pictorial\\'+ppt_num+'_'+session+'_epo.fif',overwrite=True)
imagine_audio_epochs.save(epochs_fname+'imagine_audio\\'+ppt_num+'_'+session+'_epo.fif',overwrite=True)
perception_orthographic_epochs.save(epochs_fname+'perception_orthographic\\'+ppt_num+'_'+session+'_epo.fif',overwrite=True)
perception_pictorial_epochs.save(epochs_fname+'perception_pictorial\\'+ppt_num+'_'+session+'_epo.fif',overwrite=True)
perception_audio_epochs.save(epochs_fname+'perception_audio\\'+ppt_num+'_'+session+'_epo.fif',overwrite=True)


Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
Overwriting existing file.
